name: Android Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-latest

    env:
      MODULE_NAME: androidApp
      BUILD_VARIANT: release
      JAVA_OPTS: "-Xms512m -Xmx2g -XX:MaxMetaspaceSize=512m"
      GRADLE_OPTS: "-Xms512m -Xmx2g -Dorg.gradle.daemon=false"

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      # Install Gradle dependencies
      - name: Install dependencies
        run: ./gradlew dependencies

      # Clean and build APK using Gradle with ProGuard/R8 enabled
      - name: Build APK
        run: ./gradlew clean $MODULE_NAME:assemble$BUILD_VARIANT -PenableProguard=true

      # List APK files for debugging
      - name: List APK files
        run: ls -R /Users/runner/work/kotlin/kotlin/$MODULE_NAME/build/outputs/apk/$BUILD_VARIANT

      # Copy APK files to build artifacts directory (hardcoded path)
      - name: Copy APK to artifacts
        run: |
          mkdir -p /Users/runner/work/kotlin/kotlin/build
          cp /Users/runner/work/kotlin/kotlin/$MODULE_NAME/build/outputs/apk/$BUILD_VARIANT/*.apk /Users/runner/work/kotlin/kotlin/build/

      # Copy Mapping files to build artifacts directory (if ProGuard is enabled, hardcoded path)
      - name: Copy Mapping files to artifacts
        run: |
          mkdir -p /Users/runner/work/kotlin/kotlin/build/mapping
          if [ -f /Users/runner/work/kotlin/kotlin/$MODULE_NAME/build/outputs/mapping/$BUILD_VARIANT/mapping.txt ]; then
            cp /Users/runner/work/kotlin/kotlin/$MODULE_NAME/build/outputs/mapping/$BUILD_VARIANT/mapping.txt /Users/runner/work/kotlin/kotlin/build/mapping/
          else
            echo "No mapping file found. Skipping..."
          fi

      # Upload APK as GitHub Actions artifact (hardcoded path)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: /Users/runner/work/kotlin/kotlin/build/*.apk

      # Upload Mapping as GitHub Actions artifact (hardcoded path)
      - name: Upload Mapping
        uses: actions/upload-artifact@v4
        with:
          name: android-mapping
          path: /Users/runner/work/kotlin/kotlin/build/mapping/mapping.txt
