name: Android Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-latest

    env:
      BUILD_ARTIFACTS: ${{ github.workspace }}/build
      MODULE_NAME: androidApp
      BUILD_VARIANT: release

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      # Set up Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Install Gradle dependencies
      - name: Install dependencies
        run: ./gradlew dependencies

      # Clean and build APK using Gradle
      - name: Build APK
        run: ./gradlew clean $MODULE_NAME:assemble$BUILD_VARIANT

      # Copy the APK to the artifacts folder
      - name: Copy APK to artifacts
        run: |
          mkdir -p $BUILD_ARTIFACTS
          cp -r ${{ github.workspace }}/$MODULE_NAME/build/outputs/apk/$BUILD_VARIANT/*.apk $BUILD_ARTIFACTS/

      # Copy mapping files (Proguard/R8) to artifacts folder
      - name: Copy mapping files to artifacts
        run: |
          mkdir -p $BUILD_ARTIFACTS/mapping
          cp -r ${{ github.workspace }}/$MODULE_NAME/build/outputs/mapping/$BUILD_VARIANT/mapping.txt $BUILD_ARTIFACTS/mapping/

      # Upload APK as GitHub Actions artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: $BUILD_ARTIFACTS/*.apk

      # Upload Proguard/R8 mapping files as artifact
      - name: Upload mapping files
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: android-mapping
          path: $BUILD_ARTIFACTS/mapping/mapping.txt
