name: Android Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-latest

    env:
      BUILD_ARTIFACTS: ${{ github.workspace }}/build
      MODULE_NAME: androidApp
      BUILD_VARIANT: release
      JAVA_OPTS: "-Xms512m -Xmx2g -XX:MaxMetaspaceSize=512m"
      GRADLE_OPTS: "-Xms512m -Xmx2g -Dorg.gradle.daemon=false"

    steps:
      # Checkout the code from GitHub repository (Node.js 20 compatible)
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java JDK (Node.js 20 compatible)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      # Install Gradle dependencies
      - name: Install dependencies
        run: ./gradlew dependencies

      # Clean and build APK using Gradle
      - name: Build APK
        run: ./gradlew clean $MODULE_NAME:assemble$BUILD_VARIANT -PenableProguard=true

      # Debug: List APK files
      - name: List APK files
        run: ls -R ${{ github.workspace }}/$MODULE_NAME/build/outputs/apk/$BUILD_VARIANT

      # Copy APK to the artifacts folder (make sure the path is correct)
      - name: Copy APK to artifacts
        run: |
          mkdir -p $BUILD_ARTIFACTS
          cp -r ${{ github.workspace }}/$MODULE_NAME/build/outputs/apk/$BUILD_VARIANT/*.apk $BUILD_ARTIFACTS/

      # Upload APK as GitHub Actions artifact (Node.js 20 compatible)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: $BUILD_ARTIFACTS/*.apk
